apiVersion: apps/v1
kind: Deployment
metadata:
  name: CoreAppTest
  labels:
    app: web
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 2
  progressDeadlineSeconds: 30
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        octopusexport: OctopusExport
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: dotnet-core-app-test
          image: locker77/coresdk2_1_testapp
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
